name: iba_resources_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  firebase_storage: ^11.3.0
  cloud_firestore: ^4.11.0
  lottie: ^2.7.0
  fluttertoast: ^8.2.3
  flutter_otp_text_field: ^1.1.1
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.2
  curved_navigation_bar: ^1.0.3
  flutter_native_splash: ^2.3.5
  hexagon: ^0.2.0
  percent_indicator: ^4.2.3
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  android: true
  ios: true
  web: true

  color: "#f5cb42"
  image: assets/facebook-logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/
