name: iba_resources_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  firebase_storage: ^11.3.0
  cloud_firestore: ^4.11.0
  lottie: ^2.7.0
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.2
  curved_navigation_bar: ^1.0.3
  flutter_native_splash: ^2.3.5
  percent_indicator: ^4.2.3
  font_awesome_flutter: ^10.6.0
  image_picker: ^1.0.4
  flutter_file_downloader: ^1.1.4
  file_picker: ^6.1.1
  google_fonts: ^6.1.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shimmer: ^3.0.0
  hydrated_bloc: ^9.1.3
  path_provider: ^2.1.1
  bloc_test: ^9.1.5
  mockito: ^5.4.4
  dice_bear: ^0.1.6
  flutter_svg: ^1.1.6
  golden_toolkit: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  android: true
  ios: true
  web: true

  color: "#f5cb42"
  image: assets/facebook-logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/
